name: build

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - branch: swift-5.4.3-release
            tag: 5.4.3-RELEASE
            options: '-Xmanifest -use-ld=link -Xswiftc -use-ld=link'

          - branch: swift-5.5.3-release
            tag: 5.5.3-RELEASE
            options: '-Xmanifest -use-ld=link -Xswiftc -use-ld=link'

          - branch: development
            tag: DEVELOPMENT-SNAPSHOT-2023-08-12-a
            options: ''

    steps:
      - uses: compnerd/gha-setup-swift@main
        with:
          tag: ${{ matrix.tag }}
          branch: ${{ matrix.branch }}

      - uses: actions/checkout@v3

      - name: Build
        run: swift build ${{ matrix.options }}

      - name: Test
        run: swift test ${{ matrix.options }}
