name: build

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - branch: development
            tag: DEVELOPMENT-SNAPSHOT-2025-01-31-a
            options: ''

    steps:
      - uses: compnerd/gha-setup-vsdevenv@main
        with:
          toolset_version: 14.29
          winsdk: 10.0.22621.0

      - uses: compnerd/gha-setup-swift@main
        with:
          tag: ${{ matrix.tag }}
          branch: ${{ matrix.branch }}

      - uses: actions/checkout@v3

      - name: Build
        run: swift build ${{ matrix.options }} -Xbuild-tools-swiftc -windows-sdk-root -Xbuild-tools-swiftc "${env:WindowsSdkDir}" -Xbuild-tools-swiftc -windows-sdk-version -Xbuild-tools-swiftc $env:UCRTVersion -Xbuild-tools-swiftc -Xfrontend -Xbuild-tools-swiftc -dump-clang-diagnostics

      - name: Test
        run: swift test ${{ matrix.options }}
