name: build

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest

    strategy:
      matrix:
        include:
          - branch: swift-5.4.2-release
            tag: 5.4.2-RELEASE
            options: '-Xmanifest -use-ld=link -Xswiftc -use-ld=link'

          - branch: swift-5.5-branch
            tag: 5.5-DEVELOPMENT-SNAPSHOT-2021-07-19-a
            options: '-Xmanifest -use-ld=link -Xswiftc -use-ld=link'

          - branch: development
            tag: DEVELOPMENT-SNAPSHOT-2021-07-24-a
            options: ''

    steps:
      - uses: compnerd/gha-setup-swift@main
        with:
          tag: ${{ matrix.tag }}
          branch: ${{ matrix.branch }}

      - uses: actions/checkout@v2

      - name: Build
        run: swift build ${{ matrix.options }}

      - name: Test
        run: swift test ${{ matrix.options }}
