name: coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  coverage:
    runs-on: windows-latest

    strategy:
      matrix:
        include:
          - branch: development
            tag: DEVELOPMENT-SNAPSHOT-2023-08-12-a
            options: ''

    steps:
      - uses: compnerd/gha-setup-swift@main
        with:
          tag: ${{ matrix.tag }}
          branch: ${{ matrix.branch }}

      - uses: actions/checkout@v3

      - name: Build
        run: swift build ${{ matrix.options }}

      - name: Test
        run: swift test --enable-code-coverage ${{ matrix.options }}

      - name: Process Coverage
        run: |
          llvm-cov export -format lcov -ignore-filename-regex ".build|Tests" -instr-profile .build\x86_64-unknown-windows-msvc\debug\codecov\default.profdata .build\x86_64-unknown-windows-msvc\debug\CassowaryPackageTests.xctest > coverage.lcov

      - uses: codecov/codecov-action@v3
        with:
          files: coverage.lcov
